# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lithostitched Docs
email: apollo404mc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation on the Lithostitched mod.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lithostitched.worldgen.dev/"
github_username:  Apollounknowndev

# Build settings
incremental: true
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

# JTD Theme Settings
search_enabled: true
color_scheme: green

# JTD Footer
last_edit_timestamp: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Apollounknowndev/lithostitched-docs/"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"

# JTD Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Notice
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green

include: ['_includes']